curl -X POST \
  http://127.0.0.1:8000/api/rep/licenses \
  -H 'Admin-Password: YOUR_ADMIN_PASSWORD' \
  -H 'Content-Type: application/json' \
  -d '[
  {
    "labels":[
      "AGPLv3"
    ],
    "permissions":[
      "CommericalUse",
      "derive",
	  "DerivativeWorks",
      "reproduce",
      "distribute",
      "modify"

    ],
    "obligations":[
      "Notice",
      "ShareAlike",
      "compositionShareAlike",
      "stateChange"
    ],
    "prohibitions":[
	  "holdLiable"
    ],
   "resources":[
   	{
        "description":"Your self-hosted, globally interconnected microblogging community",
        "uri":"https://github.com/tootsuite/mastodon",
        "label":"mastodon"
    }
    ]
  },
  {
    "labels":[
      "GPL-3.0",
      "EPL1.0"
    ],
    "permissions":[
      "CommericalUse",
      "derive",
	  "DerivativeWorks",
      "reproduce",
      "distribute",
      "modify"

    ],
    "obligations":[
      "Notice",
      "ShareAlike",
      "compositionShareAlike",
      "stateChange",
      "attachSource"
    ],
    "prohibitions":[
	  "holdLiable"
    ],
    "resources":[
    	{
        "description":"",
        "uri":"https://github.com/junit-team/junit4",
        "label":"junit4"
        }
    ]
  },
  {
    "labels":[
      "LGPL-3.0"
    ],
    "permissions":[
      "CommericalUse",
      "derive",
	  "DerivativeWorks",
      "reproduce",
      "distribute",
      "modify"

    ],
    "obligations":[
      "Notice",
      "ShareAlike",
      "stateChange",
      "attachSource"
    ],
    "prohibitions":[
	  "holdLiable"
    ],
    "resources":[
    	{
        "description":"",
        "uri":"https://github.com/PHPMailer/PHPMailer",
        "label":"PHPMailer"
        }
    ]
  },
  {
    "labels":[
      "AFL-3.0"
    ],
    "permissions":[
      "CommericalUse",
      "reproduce",
      "distribute",
      "modify",
      "derive",
	  "DerivativeWorks"

    ],
    "obligations":[
      "Notice",
      "stateChange",
      "attachSource"
    ],
    "prohibitions":[
      "holdLiable"
    ],
    "resources":[
    	{
        "description":"PyMC: Bayesian Stochastic Modelling in Python",
        "uri":"https://github.com/pymc-devs/pymc",
        "label":"pymc"
        }
    ]
  },
  {
    "labels":[
      "Apache v2.0"
    ],
    "permissions":[
      "CommericalUse",
      "reproduce",
      "distribute",
      "modify",
      "derive",
	  "DerivativeWorks"

    ],
    "obligations":[
      "Notice",
      "stateChange"
    ],
    "prohibitions":[
      "holdLiable"
    ],
    "resources":[
    	{
        "description":"",
        "uri":"https://github.com/tensorflow/tensorflow",
        "label":"tensorflow"
       }
    ]
  },
  {
    "labels":[
      "MPL-2.0",
      "OSL-2.0"
    ],
    "permissions":[
      "CommericalUse",
      "reproduce",
      "distribute",
      "modify",
      "derive",
	  "DerivativeWorks"

    ],
    "obligations":[
      "Notice",
      "ShareAlike",
      "attachSource"
    ],
    "prohibitions":[
	  "holdLiable"
    ],
    "resources":[
    	{
        "description":"",
        "uri":"https://github.com/bailicangdu/vue2-elm",
        "label":"vue2-elm"
      },
      {
        "description":"",
        "uri":"https://github.com/x64dbg/x64dbg",
        "label":"x64dbg"
      }
    ]
  },
  {
    "labels":[
      "BSD 3-clause",
      "BSD 2-clause",
      "MIT",
      "X11",
      "Ms-PL"
    ],
    "permissions":[
      "CommericalUse",
      "reproduce",
      "distribute",
      "modify",
	  "derive",
	  "DerivativeWorks"
    ],
    "obligations":[
      "Notice"
    ],
    "prohibitions":[
      "holdLiable"
    ],
    "resources":[
		{
	    "description":"",
	    "uri":"https://github.com/freeCodeCamp/freeCodeCamp",
	    "label":"freeCodeCamp"
	    },
	    {
        "description":"",
        "uri":"https://github.com/NickeManarin/ScreenToGif",
        "label":"ScreenToGif"
        },
        {
        "description":"Define a partial order over licenses using CaLi model",
        "uri":"https://github.com/benjimor/CaLi",
        "label":"CaLi"
        }
    ]
  },
  {
    "labels":[
      "zlib/libng"
    ],
    "permissions":[
      "CommericalUse",
      "derive",
	  "DerivativeWorks",
      "reproduce",
      "distribute",
      "modify"
    ],
    "obligations":[
      "stateChange"
    ],
    "prohibitions":[
      "holdLiable"
    ],
    "resources":[
    	{
        "description":"Simple management UI for Docker",
        "uri":"https://github.com/portainer/portainer",
        "label":"portainer"
    	}
    ]
  },
  {
    "labels":[
      "PDDL-1.0"
    ],
    "permissions":[
      "CommericalUse",
      "reproduce",
      "distribute",
      "modify",
	  "derive",
	  "DerivativeWorks"
    ],
    "obligations":[
    ],
    "prohibitions":[
      "holdLiable"
    ],
    "resources":[
    	{
        "description":"A curated list of amazingly awesome PHP libraries, resources and shiny things.",
        "uri":"https://github.com/ziadoz/awesome-php",
        "label":"awesome-php"
    	}
    ]
  },
  {
    "labels":[
      "unlicense"
    ],
    "permissions":[
      "CommericalUse",
      "reproduce",
      "distribute",
      "modify",
	  "derive",
	  "DerivativeWorks"
    ],
    "obligations":[
    ],
    "prohibitions":[
    ],
    "resources":[
    	{
        "description":"",
        "uri":"https://github.com/limetext/lime",
        "label":"lime"
    	}
    ]
  }
]'
